### ISSUE TITLE
Issues with Windows system?

### ISSUE THREAD

**Issue by jcresencia** [mongeslani/kohana-less#2]
Don't know if it is because I am using Windows but using your readme as an example I am having issues.

Config is...
return array
(
   'compress' => FALSE,
   'path' => 'public/less/',
)

Your example had
$stylesheets = array('/media/css/reset.less', '/media/css/style.less');
but apparently it seems it auto-adds the $config->path and the .less extension so it seems it should of been
$stylesheets = array('reset', 'style');

And I don't know if it is because I am on Windows but it couldn't find the files. So I modified the code where mainly it says $config->path.$filename or similar to add the DOCROOT so basically it becomes DOCROOT.$config->path.$filename.

**Comment by mongeslani** [comment]
Hello, thanks for reporting this. Sorry about that, the sample code on my README was out of date. I've updated it to add a sample for less.php in config folder, as well as updated the way I pass the less files (no extension) like what you pointed. Cheers!
