### ISSUE TITLE
Please extend your example with 'Generated Sourcecode'

### ISSUE THREAD

**Issue by 321X** [mongeslani/kohana-less#3]
Hi,

Can you extend your example with a piece of sourcecode that will be generated? 

Does it generate css file includes, or inline css code?

Your module looks nice, thanks!

**Comment by mongeslani** [comment]
Greetings, updated the module and added a sample code with the generated css file.
It generates css file includes. Cheers!

**Comment by 321X** [comment]
Okay, nice. Looks good! I'm gonna watch this project and use it.

Keep up the good work!
