### ISSUE TITLE
No error thrown when no valid input file is found

### ISSUE THREAD

**Issue by alanhogan** [mongeslani/kohana-less#4]
If `Less::compile` is run with bad input files, then instead of throwing an exception, `Less::compile` simply returns a 'file name' containing an error message.

**Comment by mongeslani** [comment]
yeah, i purposely set it that way so instead of breaking the site, you'll simply get an unstyled page.

**Comment by alanhogan** [comment]
At least in my environment though, it still breaks the site — just differently, with a failed file open call, IIRC. Since style changes don't just happen willy nilly in production, I think this type of error should cause an exception without fear it will break someone's site.

**Comment by DanHulton** [comment]
I noticed this same problem, and added the following line just above the "could not find" line:

```
Kohana::$log->add("ERROR", "Could not find LESS/CSS file: $file");
```

That way you have an error recorded in your logs, and if you run something like FirePHP, the error appears in your console as well.  The styling of the site stays the same.

**Comment by mongeslani** [comment]
Thanks for pointing this out, would like to get your updates to fix the issues as I haven't spent much time on this lately.
