### ISSUE TITLE
public static function _compile($filename) is redundant

### ISSUE THREAD

**Issue by nickolasgregory** [mongeslani/kohana-less#8]
The __generate_assets()_ method writes the concatenated _less_ file which is then overwritten by the __compile()_ method with the compiled and compressed _css_ file.

The contents of the concatenation ($data) could simply be passed to parse

```
$less->parse($data);
```

(Note $less->importDir will need to be set for _@import 'lessfile'_ to work.)

I rewrote it as a single function and can post the code or create a pull request if you like,.
Cheers and thanks for all of your work.

**Comment by mongeslani** [comment]
very cool, thanks for finding this useful. haven't spent time on it lately but I'd like to update this with your edits, cheers!
